/*
══════════════════════════════════════════════════════════════════════════════
 [FILM NEG INVERT] [1.1.0] - MAINENTRY.CPP
 [OFX entry point and factory registration.]
 [C++]
══════════════════════════════════════════════════════════════════════════════
Taller Lab - 2026
https://tallerlab.com/
VAI CORINTHIANS!!
══════════════════════════════════════════════════════════════════════════════
*/

// ===========================================
// 1. INCLUDES
// ===========================================

#include "FilmNegInvertPluginFactory.h"
#include "ofxsImageEffect.h"

// ===========================================
// 2. GLOBAL FACTORY INSTANCE
// ===========================================

static FilmNegInvert::FilmNegInvertPluginFactory gFilmNegInvertPluginFactory;

// ===========================================
// 3. OFX REGISTRATION
// ===========================================

namespace OFX {
    // OfxGetNumberOfPlugins and OfxGetPlugin are generated by the support library.
    void Plugin::getPluginIDs(OFX::PluginFactoryArray& ids)
    {
        ids.push_back(&gFilmNegInvertPluginFactory);
    }
}
